In [1]:
import os
os.chdir(r'C:\Users\82107\Desktop\Study\ML learning')
print('current directory:', os.getcwd())

current directory: C:\Users\82107\Desktop\Study\ML learning


In [5]:
# 행렬을 다루기 위한 모듈을 불러온다.
import numpy as np
# 데이터를 읽어오기 위한 pandas 모듈을 불러온다.
import pandas as pd 

np.random.seed(1)
p = 2
true_beta = np.array([[1], [0.5]])
n = 1000
x = np.random.normal(loc=0, scale=0.2, size=(n,1)) # x라는 설명변수를 정규 분포로부터 1000개를 뽑았음
x = np.hstack((np.ones((n,1)), x)) #상수항과 회귀항을 같이 분석하기 위해서 1이라는 벡터와 우리가 생성한 x벡터를 합치는 곳
x[:5, :]

array([[ 1.        ,  0.32486907],
       [ 1.        , -0.12235128],
       [ 1.        , -0.10563435],
       [ 1.        , -0.21459372],
       [ 1.        ,  0.17308153]])

In [6]:
# 모수값을 계산하고 포아송 분포를 이용해 y를 생성
parm = np.exp(x @ true_beta)
parm[:5, :]

array([[3.19770875],
       [2.55697357],
       [2.57843551],
       [2.44172105],
       [2.96400313]])

In [7]:
y = np.random.poisson(parm)
y[:5, :]

array([[4],
       [2],
       [2],
       [3],
       [1]])

In [8]:
beta = np.array([.5, .5]).reshape((p, 1)) #beta값은 0.5, 0.5
#1차 미분
parm = np.exp(x @ beta)
grad = -np.mean(y*x - parm*x, axis=0).reshape((p,1)) #gradiend descent에서 사용할 변수
grad

array([[-1.07590006],
       [-0.03620562]])

In [9]:
learning_rate = 0.7
#initial beta
beta = np.zeros((p, 1)) #초기 솔루션은 0으로부터 시작
for i in range(500):
    #모수추정값, 1차 미분 계산
    parm = np.exp(x @ beta)
    grad = -np.mean(y*x - parm*x, axis=0).reshape((p,1))
    
    #beta update
    beta_new = beta - learning_rate*grad
    
    #stopping rule, 해가 수렴할때 까지 반복
    if np.sum(np.abs(beta_new - beta)) < 1e-8:
        beta = beta_new
        print('Iteration {} beta: '.format(i+1))
        print(beta, '\n')
        break
    else:
        beta = beta_new
        print('Iteration {} beta: '.format(i+1))
        print(beta, '\n')

Iteration 1 beta: 
[[1.2173    ]
 [0.05128819]] 

Iteration 2 beta: 
[[0.76890038]
 [0.08497731]] 

Iteration 3 beta: 
[[1.17481907]
 [0.12502591]] 

Iteration 4 beta: 
[[0.82294632]
 [0.15322112]] 

Iteration 5 beta: 
[[1.14358892]
 [0.18814092]] 

Iteration 6 beta: 
[[0.85957336]
 [0.2118515 ]] 

Iteration 7 beta: 
[[1.11921502]
 [0.24220564]] 

Iteration 8 beta: 
[[0.88634236]
 [0.26222014]] 

Iteration 9 beta: 
[[1.09956325]
 [0.28854142]] 

Iteration 10 beta: 
[[0.90677746]
 [0.30548869]] 

Iteration 11 beta: 
[[1.0834115 ]
 [0.32826791]] 

Iteration 12 beta: 
[[0.92281526]
 [0.34265599]] 

Iteration 13 beta: 
[[1.06997847]
 [0.36233765]] 

Iteration 14 beta: 
[[0.93563883]
 [0.37458085]] 

Iteration 15 beta: 
[[1.05872319]
 [0.39156291]] 

Iteration 16 beta: 
[[0.94602687]
 [0.40200151]] 

Iteration 17 beta: 
[[1.04924815]
 [0.41663734]] 

Iteration 18 beta: 
[[0.95452114]
 [0.42555254]] 

Iteration 19 beta: 
[[1.04124817]
 [0.43815396]] 

Iteration 20 beta: 
[[0.96151472]
 [0.44

In [11]:
beta = np.array([.5, .5]).reshape((p,1))
# 2차 미분
parm = np.exp(x @ beta)
D = np.diag(np.squeeze(parm))
D

array([[1.9395084 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.55088286, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 1.56390019, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 1.63728199, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 1.70810923,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        1.61818394]])

In [13]:
H = x.T @ D @ x/n
H

array([[1.66309994, 0.04482571],
       [0.04482571, 0.06487878]])

In [14]:
# initial beta
beta = np.zeros((p, 1))
for i in range(500):
    # 모수추정값, 1차와 2차 미분 계산
    parm = np.exp(x @ beta)
    grad = -np.mean(y*x - parm*x, axis=0).reshape((p,1))
    D = np.diag(np.squeeze(parm))
    H = x.T @ D @ x/n
    
    # beta update
    beta_new = beta - np.linalg.inv(H) @ grad #역행렬을 구하는 줄이 추가되었음(해를 갱신할 때 H의 역행렬이 필요함)
    
    # stopping rule
    if np.sum(np.abs(beta_new - beta)) < 1e-8:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')
        break
    else:
        beta = beta_new
        print('Iteration {} beta:'.format(i+1))
        print(beta, '\n')

Iteration 1 beta:
[[1.72694737]
 [1.55267496]] 

Iteration 2 beta:
[[1.21680451]
 [1.10098661]] 

Iteration 3 beta:
[[1.02354269]
 [0.68242648]] 

Iteration 4 beta:
[[0.99755109]
 [0.57208561]] 

Iteration 5 beta:
[[0.99696661]
 [0.56874834]] 

Iteration 6 beta:
[[0.99696623]
 [0.5687461 ]] 

Iteration 7 beta:
[[0.99696623]
 [0.5687461 ]] 

