In [1]:
import numpy as np

a = np.array([1, 2, 3]) # 1차원 배열로 벡터를 나타냄
print(a)

b = np.array([-2.4, 0.25, -1.3, 1.8, 0.61])
print(b)

[1 2 3]
[-2.4   0.25 -1.3   1.8   0.61]


In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2x3 행렬
print(a)

b = np.array([[0.21, 0.14],
              [-1.3, 0.81],
              [0.12, -2.1]])    # 3x2 행렬
print(b)

[[1 2 3]
 [4 5 6]]
[[ 0.21  0.14]
 [-1.3   0.81]
 [ 0.12 -2.1 ]]


In [3]:
a = np.array([[[0, 1, 2, 3],
               [2, 3, 4, 5],
               [4, 5, 6, 7]],
               [[1, 2, 3, 4],
                [3, 4, 5, 6],
                [5, 6, 7, 8]]]) # (2, 3, 4)의 3차원 텐서

print(a)

[[[0 1 2 3]
  [2 3 4 5]
  [4 5 6 7]]

 [[1 2 3 4]
  [3 4 5 6]
  [5 6 7 8]]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print('--- dot() 함수 ---')
print(np.dot(a, b)) # dot() 함수에 의한 내적
print('--- 곱의 총합 ---')
print(np.sum(a * b)) # 곱의 총합에 의한 내적

--- dot() 함수 ---
10
--- 곱의 총합 ---
10


In [5]:
a = np.array([1, 1, -1, -1])

print('--- L2놈 ---')
print(np.linalg.norm(a))    #L2놈(디폴트)
print('--- L1놈 ---')
print(np.linalg.norm(a, 1)) #L1놈

--- L2놈 ---
2.0
--- L1놈 ---
4.0


In [6]:
a = np.array([1, -2, 2])
b = np.array([2, -2, 1])

print('--- 내적 ---')
print(np.dot(a, b))
print('--- L2놈 ---')
print(np.linalg.norm(a))
print('--- L1놈 ---')
print(np.linalg.norm(a, 1))

--- 내적 ---
8
--- L2놈 ---
3.0
--- L1놈 ---
5.0


In [7]:
#행렬의 곱

a = np.array([[0, 1, 2],
             [1, 2, 3]])

b = np.array([[2, 1],
              [2, 1],
              [2, 1]])

print(np.dot(a, b))

[[ 6  3]
 [12  6]]


In [8]:
#요소별 곱(아다마르 곱)

a = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

b = np.array([[0, 1, 2],
              [2, 0, 1],
              [1, 2, 0]])

print(a*b)

[[ 0  1  4]
 [ 6  0  5]
 [ 6 14  0]]


In [10]:
a = np.array([[0, 1, 2],
              [1, 2, 3]])

b = np.array([[0, 1],
              [1, 2],
              [2, 3]])

# 행렬곱
print(np.dot(a, b))

print()

c = np.array([[0, 1, 2],
              [3, 4, 5],
              [6, 7, 8]])

d = np.array([[0, 2, 0],
              [2, 0, 2],
              [0, 2, 0]])

# 아다마르 곱
print(c*d)

[[ 5  8]
 [ 8 14]]

[[ 0  2  0]
 [ 6  0 10]
 [ 0 14  0]]
