In [5]:
import os
os.chdir(r'C:\Users\82107\바탕 화면\Study\ML learning')
print('current directory:', os.getcwd())

current directory: C:\Users\82107\바탕 화면\Study\ML learning


In [3]:
import numpy as np
# 선형회귀모형을 사용할 수 있는 모듈을 불러온다.
import statsmodels.api as sm

# 관측치의 개수
N = 1000
# 정규분포를 이용해 데이터를 생성(N(0, 1) 분포)
X = np.random.normal(loc=0, scale=1, size=(N, 1)) #행이 1000개, 열이 1개
#회귀모형 적합을 위해 addconstant 실행
X = sm.add_constant(X) # 절편(상수항)을 추가(앞에 상수항이 들어감)
X[:6, :]

array([[ 1.        ,  0.89811432],
       [ 1.        , -0.02718075],
       [ 1.        ,  2.61593041],
       [ 1.        ,  1.29053215],
       [ 1.        ,  1.09207876],
       [ 1.        , -0.09553763]])

In [4]:
epsilon = np.random.normal(loc=0, scale=1, size=(N, 1))

# 실제 모형: Y = 2 + 3X + epsilon, @는 행렬의 곱을 의미
Y = X @ np.array([[2], [3]]) + epsilon
# [2]가 beta 0, [3]이 beta 1이 됨

Y[:6, :] #생성된 처음 6개를 살펴보기 위해

#회귀모형을 따르는 X, Y 생성

array([[6.00669699],
       [2.63681158],
       [8.72700583],
       [4.98844485],
       [5.74804978],
       [1.50819393]])

In [9]:
#단순회귀모형 적합
simple_reg = sm.OLS(Y, X).fit()
# 적합 결과 확인
simple_reg.summary()

#const가 beta0의 햇, x1이 beta1의 햇

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.901
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     9098.
Date:                Tue, 10 Oct 2023   Prob (F-statistic):               0.00
Time:                        22:40:08   Log-Likelihood:                -1423.8
No. Observations:                1000   AIC:                             2852.
Df Residuals:                     998   BIC:                             2861.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.0171      0.032     63.402      0.000       1.955       2.079
x1             3.0363      0.032     95.382      0.000       2.974       3.099
==============================================================================
Omnibus:                        1.094   Durbin-Watson:                   2.061
Prob(Omnibus):                  0.579   Jarque-Bera (JB):                1.131
Skew:                          -0.079   Prob(JB):                        0.568
Kurtosis:                       2.955   Cond. No.                         1.02
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [10]:
# 관측치의 개수
N = 1000
# 모형 적합을 반복하는 횟수
repeat_num = 1000

beta = np.zeros((2, ))
for k in range(repeat_num):
    # 정규분포를 이용해 데이터를 생성(N(0, 1) 분포)
    X = np.random.normal(loc=0, scale=1, size=(N, 1))   
    # 절편(상수항)을 추가
    X = sm.add_constant(X)
    # 정규분포를 이용해 오차항을 생성(N(0, 1) 분포)
    epsilon = np.random.normal(loc=0, scale=1, size=(N, 1))
    # 실제 모형: Y = 2 + 3X + epsilon
    Y = X @ np.array([[2], [3]]) + epsilon
    
    simple_reg = sm.OLS(Y, X).fit()
    beta += simple_reg.params
    
# 적합된 회귀 계수의 평균을 계산
beta /= repeat_num
beta

#이 beta가 모델의 bias를 계산할 때 사용하는 추정량의 평균

array([1.99914503, 2.99805972])

In [11]:
# 관측치의 개수
N = 1000
# 모형 적합을 반복하는 횟수
repeat_num = 1000

beta = np.zeros((2, ))
for k in range(repeat_num):
    # 정규분포를 이용해 데이터를 생성(N(0, 1) 분포)
    X = np.random.normal(loc=0, scale=1, size=(N, 1))   
    # 절편(상수항)을 추가
    X = sm.add_constant(X)
    # 정규분포를 이용해 오차항을 생성(N(0, 1) 분포)
    epsilon = np.random.normal(loc=0, scale=1, size=(N, 1))
    # 실제 모형: Y = 2 + 3X + epsilon
    Y = X @ np.array([[2], [3]]) + epsilon
    
    simple_reg = sm.OLS(Y, X).fit()
    beta += simple_reg.params
    
# 적합된 회귀 계수의 평균을 계산
beta /= repeat_num
beta
#참값은 beta0이 2, beta1이 3이므로 참값과 유사함을 알 수 있음

array([1.99833866, 3.0006771 ])

In [12]:
import pandas as pd

advertising = pd.read_csv('advertising.csv', encoding='cp949', index_col=0)
# TV 변수를 선택, numpy 행렬로 변환
X = np.array(advertising[['TV']])
# 절편(상수항)을 추가
X = sm.add_constant(X)
X[:6, :]
#2번째 열은 tv에 관한 광고지출 predictor

array([[  1. , 230.1],
       [  1. ,  44.5],
       [  1. ,  17.2],
       [  1. , 151.5],
       [  1. , 180.8],
       [  1. ,   8.7]])

In [13]:
Y = np.array(advertising[['sales']])
Y[:6, :]

# 단순회귀모형 적합
simple_reg = sm.OLS(Y, X).fit()
# 적합 결과 확인
simple_reg.summary()

#추정 모형 결과를 통해 y hat = 7.0326 + (0.0475 * TV 광고비)임을 알 수 있음

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.610
Method:                 Least Squares   F-statistic:                     312.1
Date:                Tue, 10 Oct 2023   Prob (F-statistic):           1.47e-42
Time:                        22:54:06   Log-Likelihood:                -519.05
No. Observations:                 200   AIC:                             1042.
Df Residuals:                     198   BIC:                             1049.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.0326      0.458     15.360      0.000       6.130       7.935
x1             0.0475      0.003     17.668      0.000       0.042       0.053
==============================================================================
Omnibus:                        0.531   Durbin-Watson:                   1.935
Prob(Omnibus):                  0.767   Jarque-Bera (JB):                0.669
Skew:                          -0.089   Prob(JB):                        0.716
Kurtosis:                       2.779   Cond. No.                         338.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [14]:
#predictor가 두개 이상일 때
import pandas as pd 

# csv 파일 형식으로 되어있는 mtcars 데이터를 불러온다.
advertising = pd.read_csv('advertising.csv', encoding='cp949', index_col=0) 
# 모든 설명 변수를 선택, numpy 행렬로 변환
X = np.array(advertising[['TV', 'radio', 'newspaper']])
# 절편(상수항)을 추가
X = sm.add_constant(X)
X[:6, :]

array([[  1. , 230.1,  37.8,  69.2],
       [  1. ,  44.5,  39.3,  45.1],
       [  1. ,  17.2,  45.9,  69.3],
       [  1. , 151.5,  41.3,  58.5],
       [  1. , 180.8,  10.8,  58.4],
       [  1. ,   8.7,  48.9,  75. ]])

In [15]:
# response variable인 'sales'를 numpy 행렬로 변환
Y = np.array(advertising[['sales']])
Y[:6, :]

# 다변량회귀모형 적합
multi_reg = sm.OLS(Y, X).fit()
# 적합 결과 확인
multi_reg.summary()
# y hat = 2.9389 + 0.0458*TV + 0.1885*radio - 0.0010*newspaper

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.897
Model:                            OLS   Adj. R-squared:                  0.896
Method:                 Least Squares   F-statistic:                     570.3
Date:                Tue, 10 Oct 2023   Prob (F-statistic):           1.58e-96
Time:                        22:59:47   Log-Likelihood:                -386.18
No. Observations:                 200   AIC:                             780.4
Df Residuals:                     196   BIC:                             793.6
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          2.9389      0.312      9.422      0.000       2.324       3.554
x1             0.0458      0.001     32.809      0.000       0.043       0.049
x2             0.1885      0.009     21.893      0.000       0.172       0.206
x3            -0.0010      0.006     -0.177      0.860      -0.013       0.011
==============================================================================
Omnibus:                       60.414   Durbin-Watson:                   2.084
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              151.241
Skew:                          -1.327   Prob(JB):                     1.44e-33
Kurtosis:                       6.332   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
# 관측치의 개수
N = 1000
# 정규분포를 이용해 데이터를 생성(N(0, 1) 표준정규분포)
X = np.random.normal(loc=0, scale=1, size=(N, 4)) #행이 1000개, 열이 4개
X[:6, :]

array([[ 1.1434812 , -0.2336136 ,  0.56295916,  1.94849086],
       [-2.5908859 ,  1.95727645, -1.03350155,  1.31536357],
       [-0.14798999, -0.8597184 , -0.88815635,  0.22706742],
       [ 1.0183621 ,  0.52599551,  0.63307851,  1.05421471],
       [-1.54748408, -1.97772675,  0.28918506,  0.108616  ],
       [-0.21939293, -1.57869333,  1.03524165, -0.57749402]])

In [19]:
# 실제 회귀 계수
beta = np.array([[0], [3], [1], [0]]) # 1번째, 4번째 predictor는 중요하지 않다는 것을 가정, 2번째와 3번째 predictor가 추정하는데 중요
beta

array([[0],
       [3],
       [1],
       [0]])

In [20]:
# 정규분포를 이용해 오차항을 생성(N(0, 1) 표준정규분포)
epsilon = np.random.normal(loc=0, scale=1, size=(N, 1)) #평균이 0 분산이 1인 정규분포
# 참 모형: Y = 0*X1 + 3*X2 + 1*X3 + 0*X4 + epsilon
Y = X @ beta + epsilon
Y[:6, :]
#intercept는 고려하지 않음

array([[ 1.05457336],
       [ 5.44201629],
       [-3.40340634],
       [ 2.40365259],
       [-5.78023801],
       [-4.25768218]])

In [26]:
# 평가할 후보 변수
candidates = list(range(4))
candidates

[0, 1, 2, 3]

In [27]:
# step. 1
bic = []
for predictor in candidates:
    # 회귀모형 적합
    reg = sm.OLS(Y, X[:, predictor]).fit()
    # BIC 값 저장
    bic.append(reg.bic)
bic
#처음에는 bic 값이 가장 작은 2번째 변수가 모델로 들어와야 함

[5193.464246178239, 3503.3237039473815, 5106.496635240852, 5193.258895008812]

In [28]:
# BIC 값이 가장 작은 변수를 선택
chosen1 = np.argmin(bic)
chosen1 

# 선택한 변수를 후보에서 제외
del candidates[chosen1]
candidates

[0, 2, 3]

In [29]:
# step. 2
bic = []
for predictor in candidates:
    # 선택한 설명 변수를 포함하여 회귀모형 적합
    reg = sm.OLS(Y, X[:, [chosen1, predictor]]).fit()
    # BIC 값 저장
    bic.append(reg.bic)
bic
#세번째 predictor([2])를 추가했을 때 bic값이 제일 작음

[3509.2944069438677, 2824.0378863753663, 3509.5147365679286]

In [30]:
chosen2 = np.argmin(bic)
chosen2

# 선택한 변수를 후보에서 제외
del candidates[chosen2]
candidates

[0, 3]

In [ ]:
# step. 3
bic = []
for predictor in candidates:
    # 선택한 설명 변수를 포함하여 회귀모형 적합
    reg = sm.OLS(Y, X[:, [chosen1, chosen2, predictor]]).fit()
    # BIC 값 저장
    bic.append(reg.bic)
bic

#candidate 값이 빈 리스트가 될 때 까지 반복 수행